pipeline {
    agent any

    stages {
        stage('Repository') {
            steps {
                git branch: 'main', url: "https://github.com/RyuKwanKon/test-wrtc-client"
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'kakao-jenkins-token', passwordVariable: 'PASSWORD_KEY', usernameVariable: 'USER_KEY')]) {
                    sh "docker login gcu-bootstrap-dev.kr-central-2.kcr.dev --username ${USER_KEY} --password ${PASSWORD_KEY}"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                withCredentials([
                    string(credentialsId: 'docker-hub-name', variable: 'DOCKER_NAME'),
                    string(credentialsId: 'docker-file-webrtc', variable: 'DOCKER_FILE'),
                ]) {
                    sh "docker build -t ${DOCKER_NAME}/${DOCKER_FILE}:${currentBuild.number} . "
                    sh "docker tag ${DOCKER_NAME}/${DOCKER_FILE}:${currentBuild.number} gcu-bootstrap-dev.kr-central-2.kcr.dev/moldev-repository/${DOCKER_FILE}:${currentBuild.number}"
                }
            }

        }

        stage('Push Docker Image') {
            steps {
                withCredentials([
                    string(credentialsId: 'docker-file-webrtc', variable: 'DOCKER_FILE')
                ]) {
                    sh "docker push gcu-bootstrap-dev.kr-central-2.kcr.dev/moldev-repository/${DOCKER_FILE}:${currentBuild.number}"
                }
            }
        }

        stage("Clone Manifest Git Repository") {
            steps {
                git(
                    url: 'https://github.com/KEA-4th-Bootstrap/moldev-kubernetes-manifest',
                    branch: "main",
                    changelog: true,
                    poll: true
                )
            }
        }

        stage("Update Manifest version changes") {
            steps {
                withCredentials([
                    string(credentialsId: 'docker-hub-name', variable: 'DOCKER_NAME'),
                    string(credentialsId: 'docker-file-webrtc', variable: 'DOCKER_FILE')
                ]) {
                    sh """
                        cd webrtc
                        sed -i 's/${DOCKER_NAME}\\/${DOCKER_FILE}:.*\$/${DOCKER_NAME}\\/${DOCKER_FILE}:${currentBuild.number}/g' deployment.yaml
                        git add deployment.yaml
                        git commit -m '[UPDATE] manifest ${currentBuild.number} image versioning'
                    """
                }
            }
        }

        stage("Push to Git Repository") {
            steps {
                withCredentials([gitUsernamePassword(credentialsId: 'git-jenkins-manifest', gitToolName: 'Default')]) {
                    sh "git push -u origin main"
                }
            }
        }
    }
}